Allow kwargs in network creation to override Class-level variables for Roadway and Transit
wsp-sag/network_wrangler pull request #312
Opened 2023-03-02 01:17 UTC by e-lo

This PR adds steps to the `read()` function for both RoadwayNetwork and TransitNetwork which will read in kwargs from the `read()` variables and will update any matching (upper-case) class-level variables to the specified values.

This is useful for when an agency might need to use a different unique ID or variable set from the defaults. 

Also:
- added util method: `class_vars()`
- test network links which use different Key than `model_link_id`

Tested via: `test_kwarg_instantiation()`

Closes Issue #290

2023-07-06 19:34 UTC, i-am-sijia requested changes

2023-07-06 19:34 UTC, i-am-sijia commented on tests/test_roadway.py
> +        link_file=SMALL_LINK_FILE,
Shouldn't we be testing with the link_diffIDs.json?

2023-07-06 19:34 UTC, i-am-sijia commented on network_wrangler/roadwaynetwork.py
> +    UNIQUE_MODEL_LINK_IDENTIFIERS = [UNIQUE_LINK_KEY]
In the example test [`test_kwarg_instantiation()`](https://github.com/wsp-sag/network_wrangler/blob/06740ad41b26418c7ef1276260fc9e59c9b0df0f/tests/test_roadway.py#L1252C8-L1252C8) in test_roadway.py, we update the `UNIQUE_LINK_KEY` to `"different_link_id"`, which works, but it does not automatically update the reference of `UNIQUE_LINK_KEY` in the class, i.e., the `UNIQUE_MODEL_LINK_IDENTIFIEDS` here would still be `["model_link_id"]`, which is causing the test using "links_DiffIDs.json" to fail.

We need to refresh all class attrs whenever setattr() is called.

2023-07-06 19:34 UTC, i-am-sijia commented on network_wrangler/transitnetwork.py
> +            setattr(RoadwayNetwork,k.upper(),v)
Here for the same issue in roadwaynetwork.py

2023-07-06 19:34 UTC, i-am-sijia commented on network_wrangler/roadwaynetwork.py
> +            setattr(RoadwayNetwork,k.upper(),v)
after this setattr(), can we refresh all the attrs?

2023-07-06 19:34 UTC, i-am-sijia commented on tests/test_roadway.py
> +        link_file=SMALL_LINK_FILE,
Test fails when using the link_diffIDs.json. Error:

```python
2023-07-06 15:20:19, ERROR: Network doesn't contain unique link identifier: model_link_id
```

2024-08-21 19:54 UTC, e-lo commented
Closing this as this approach has been superceeded by aligning on a string model for IDs across all tables in the `selection-refactor` branch.

2024-08-21 19:54 UTC, closed without merging